All: CtoF FtoC Negate FeetToInches InchesToFeet MultiplyTen Swap

CtoF: CtoF.s
	gcc CtoF.s -g -o CtoF

FtoC: FtoC.s
	gcc FtoC.s -g -o FtoC

Negate: Negate.s
	gcc Negate.s -g -o Negate

FeetToInches: FeetToInches.s
	gcc FeetToInches.s -g -o FeetToInches

InchesToFeet: InchesToFeet.s
	gcc InchesToFeet.s -g -o InchesToFeet

MultiplyTen: MultiplyTen.s
	gcc MultiplyTen.s -g -o MultiplyTen

Swap: Swap.s
	gcc Swap.s -g -o Swap

