All: computerGuessNumber guessComputerNumber 

computerGuessNumber: computerGuessNumber.s
	gcc computerGuessNumber.s -g -o computerGuessNumber

guessComputerNumbeer: guessComputerNumber.s
	gcc guessComputerNumber.s -g -o guessComputerNumber

